version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - minio
    environment:
      - REDIS_URL=redis://host.docker.internal:6379/0
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn auction_webapp.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --timeout 120"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - minio
      - web
    environment:
      - REDIS_URL=redis://host.docker.internal:6379/0
    command: celery -A auction_webapp worker --loglevel=info
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"

volumes:
  minio_data: 