# Generated by Django 5.0.7 on 2024-09-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_taskprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='status',
            field=models.TextField(),
        ),
    ]
