# Generated by Django 5.0.7 on 2024-09-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_taskprogress_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
