# Generated by Django 5.0.7 on 2024-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_delete_taskprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('warehouse', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
