# Generated by Django 5.0.7 on 2024-09-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_imagemetadata_voidedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.CreateModel(
            name='AuctionFormattedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatted_data', to='auction.event')),
            ],
        ),
        migrations.CreateModel(
            name='HiBidUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('lot_count', models.IntegerField(default=0)),
                ('auction_id', models.CharField(max_length=100)),
                ('ending_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hibid_uploads', to='auction.event')),
            ],
        ),
    ]
