# Generated by Django 5.0.7 on 2024-09-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_imagemetadata_image_auctionformatteddata_hibidupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='image',
            field=models.URLField(default='https://example.com/placeholder-image.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
