# Generated by Django 5.0.7 on 2024-09-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_imagemetadata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hibidupload',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='hibidupload',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='hibidupload',
            name='lot_count',
        ),
    ]
